### ISSUE TITLE
WTF are we making

### ISSUE THREAD

**Issue by Imacds** [Imacds/ship-project-cs4700#1]
We need to figure out what game we are cloning.

**Comment by Imacds** [comment]
Games we have interest in so far: 
- Galaga
-  Pitfall
- Dig Dug

**Comment by indigoxv7** [comment]
I'm down for Galaga

**Comment by jtara1** [comment]
I'll vote for Galaga.

**Comment by jtara1** [comment]
players were pretty positive during their init play test. The big selling point was just the enemy movement, great job @Imacds 

complaints were mostly about player ship firing mechanics, firing was too slow, took too long to charge, or didn't have enough juice with this mechanic for feedback.
